version: "3.8"

services:
  mysql:
    image: mysql:9.4.0
    container_name: mysql-container
    restart: always
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:    
      - mysql_data:/var/lib/mysql
      - ./src/main/resources/init.sql:/docker-entrypoint-initdb.d/0_init.sql
      - ./src/main/resources/schema.sql:/docker-entrypoint-initdb.d/1_schema.sql
      - ./src/main/resources/data.sql:/docker-entrypoint-initdb.d/2_data.sql

volumes:
  mysql_data:
