version: "3.8"

services:
  mysql:
    image: mysql:9.4.0
    container_name: mysql-container
    restart: always
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:    
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
