services:
  mysql:
    image: mysql:9.4.0
    container_name: mysql-container
    restart: always
    env_file:
      - .env
    ports:
      - "3306:3306"
    volumes:    
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -uroot -p$MYSQL_ROOT_PASSWORD || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s

  backend:
    build: .
    container_name: springboot-container
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
    env_file:
      - .env
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/${MYSQL_DATABASE}
      SPRING_DATASOURCE_USERNAME: ${DB_USER}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD}

volumes:
  mysql_data:
    driver: local
    driver_opts:
      type: none
      device: ${MYSQL_VOLUME_PATH}
      o: bind
